config/routes.rb
Fruitstand::Application.routes.draw do

  get '/cart' => "cart#show", as: 'cart'
  post '/cart/add_item/:product_id' => "cart#add_item", as: 'add_item_cart'
  post '/cart/remove_item/:line_item_id' => "cart#remove_item", as: 'remove_item_cart'
  post '/checkout' => "cart#checkout", as: 'checkout_cart'

  root :to => 'products#index'

end

app/models/cart.rb
class Cart < ActiveRecord::Base
  # attr_accessible :title, :body
  #
  has_many :line_items, as: :itemable, dependent: :destroy


  monetize :total_cents

  def total_cents
    line_items.sum(&:total_cents)
  end

end

app/models/line_item.rb
class LineItem < ActiveRecord::Base

  attr_accessible :price, :product, :quantity

  belongs_to :itemable, polymorphic: true
  belongs_to :product


  before_create :save_price

  monetize :total_cents, allow_nil: true

  def total_cents
    price.present? ? quantity * price : 0
  end

  def price_to_s
    sprintf('%.2f', price / 100.0)
  end

  private

    def save_price
      self.price = product.price
    end


end

app/models/order.rb
class Order < ActiveRecord::Base
  # attr_accessible :title, :body
  #
  has_many :line_items, as: :itemable


  def bill
    true
  end
end

app/models/product.rb
class Product < ActiveRecord::Base

  attr_accessible :name, :price

  has_many :line_items

  validates :name, presence: true, uniqueness: true
  validates :price, presence: true, numericality: true

  validates :name, :price, presence: true
  validates :name, uniqueness: true
  validates :price, numericality: true

  validates_presence_of :name, :price
  validates_numericality_of :price
  validates_uniqueness_of :name

  def price_to_s
    price / 100

  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

end

app/controllers/cart_controller.rb
class CartController < ApplicationController

  def show
    if session[:cart_id]
      @cart = Cart.find(session[:cart_id])
    else
      @cart = Cart.create
      session[:cart_id] = @cart.id
    end
  end

  def add_item
    if session[:cart_id]
      @cart = Cart.find(session[:cart_id])
    else
      @cart = Cart.create
      session[:cart_id] = @cart.id
    end
    @product = Product.find(params[:product_id])
    unless @line_item = @cart.line_items.find_by_product_id(@product.id)
      @line_item = @cart.line_items.build(product: @product, quantity: 1)
    else
      @line_item.quantity += 1
    end
    if @line_item.save
      flash[:notice] = "#{@product.name} added to cart"
      redirect_to root_path
    end
  end

  def remove_item
    @cart = Cart.find(session[:cart_id])
    @line_item = @cart.line_items.find(params[:line_item_id])
    if @line_item.destroy
      flash[:notice] = "#{@line_item.product.name} removed from cart"
      redirect_to cart_path
    end
  end

  def checkout
    @cart = Cart.find(session[:cart_id])
    @order = Order.create
    @cart.line_items.each do |line_item|
      @order.line_items << LineItem.new({product: line_item.product, quantity: line_item.quantity})
    end
    @order.save
    if @order.bill
      session[:cart_id] = nil
      @cart.destroy
      flash[:notice] = "Thank you for completing your order"
      redirect_to root_path
    end
  end

  def thank_you
  end



end

app/controllers/products_controller.rb
class ProductsController < ApplicationController


  def index
    @products = Product.all
    if session[:cart_id]
      @cart = Cart.find(session[:cart_id])
    else
      @cart = Cart.create
      session[:cart_id] = @cart.id
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/cart/show.html.erb
<%= link_to "Continue Shopping", root_path %>
<table class='table'>
  <thead>
    <tr>
      <th>Product</th>
      <th>Price</th>
      <th>Quantity</th>
      <th>Total</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
<% @cart.line_items.each do |line_item| %>
  <tr>
    <td><%= line_item.product.name %></td>
    <td>$<%= line_item.price_to_s %></td>
    <td><%= line_item.quantity %></td>
    <td>$<%= line_item.total %></td>
    <td><%= link_to "Remove Item", remove_item_cart_path(line_item.id), :method => :post, confirm: "Are you sure?", class: 'btn btn-danger' %></td>
  </tr>
<% end %>
  <tr>
    <td colspan='3' style='text-align: right'><strong>Cart Total is:</strong></td>
    <td> $<%= @cart.total %></td>
    <td>&nbsp;</td>
  </tr>
</tbody>
</table>
<p><%= link_to "Checkout", checkout_cart_path, :method => :post %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Fruitstand</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/products/index.html.erb
<%= link_to "Cart has #{@cart.line_items.size} item(s)", cart_path %>
<table class='table'>
  <thead>
    <tr>
      <th>Product</th>
      <th>Price</th>
      <th>Tasks</th>
    </tr>
  </thead>
  <tbody>
<% @products.each do |product| %>
  <tr>
    <td><%= product.name.capitalize %></td>
    <td>$<%= sprintf('%.2f', product.price / 100.0) %></td>
    <td><%= link_to "Add To Cart", add_item_cart_path(product.id), :method => :post, class: 'btn btn-primary' %></td>
  </tr>
<% end %>
  </tbody>
</table>